DROP TABLE WM_AD_HOC.FACE_FEE_PAYMENT;
CREATE  TABLE WM_AD_HOC.FACE_FEE_PAYMENT AS (

SELECT s.STORE_NBR, v.VISIT_NBR,
s.VISIT_DATE, i.ITEM_NBR, i.ITEM1_DESC, s.RETAIL_PRICE, s.UNIT_QTY, s.Returned_item_ind, v.VOID_CMPLT_TRANS_IND, s.VOIDED_ITEM_IND,
CASE   WHEN s.RETAIL_PRICE > 0 THEN '+' ELSE '-' END AS AMOUNT_SIGN,
CASE WHEN s.VOIDED_ITEM_IND = 1 THEN 'Voids' WHEN s.Returned_item_ind =1 THEN 'Returns' ELSE'Transactions' END AS TRANS_TYPE,
tcash.CASH_Payment, tcards.CARDS_Payment

FROM us_wm_mb_vm.scan s INNER JOIN us_wm_mb_vm.visit v ON s.VISIT_DATE = v.VISIT_DATE AND s.STORE_NBR = v.STORE_NBR AND s.VISIT_NBR = v.VISIT_NBR 
INNER JOIN us_wm_vm.item i ON s.SCAN_ID = i.ITEM_NBR 
LEFT JOIN 

(SELECT  VISIT_NBR, STORE_NBR,VISIT_DATE, SUM(TENDER_AMT) AS CASH_Payment
FROM us_wm_mb_vm.visit_tender t 
--WHERE VISIT_DATE BETWEEN DATE '2019-04-09' AND DATE  '2020-01-01'
WHERE  t.TENDER_TYPE = 15
GROUP BY 1,2,3) tcash  ON s.VISIT_DATE = tcash.VISIT_DATE AND s.STORE_NBR =  tcash.STORE_NBR AND s.VISIT_NBR = tcash.VISIT_NBR 

LEFT JOIN 
(SELECT  VISIT_NBR, STORE_NBR,VISIT_DATE, SUM(TENDER_AMT) AS CARDS_Payment
FROM us_wm_mb_vm.visit_tender t 
WHERE  t.TENDER_TYPE <> 15
GROUP BY 1,2,3) tcards  ON s.VISIT_DATE = tcards.VISIT_DATE AND s.STORE_NBR = tcards.STORE_NBR AND s.VISIT_NBR =tcards.VISIT_NBR 




WHERE 
s.VISIT_DATE BETWEEN  DATE '2019-04-19' AND DATE  '2020-01-01'

AND s.SCAN_ID IN (
120703658,53971238, ---Money Order Fee
120703560,53970175, --- Money Order Face
151715874                   --- Money Order Vendor Payment
)
) WITH DATA;

SELECT
a.Visit_YEAR, a.Visit_Month
,a.STORE_NBR
,a.ITEM1_DESC
,a.TRANS_TYPE
,a.Trans_Amount
,a.Trans_Count
,b.Sum_Cash
,b.Sum_Card_Payment
FROM

(SELECT  

EXTRACT (YEAR FROM VISIT_DATE)AS Visit_YEAR
,EXTRACT (MONTH FROM VISIT_DATE)AS Visit_Month

,STORE_NBR
,ITEM1_DESC
,TRANS_TYPE

,SUM(RETAIL_PRICE) AS Trans_Amount
,COUNT(DISTINCT(VISIT_NBR)) AS Trans_Count
GROUP BY 1,2,3,4,5

FROM  WM_AD_HOC.FACE_FEE_PAYMENT) a



LEFT JOIN 

(

SELECT 

EXTRACT (YEAR FROM VISIT_DATE)AS Visit_YEAR
,EXTRACT (MONTH FROM VISIT_DATE)AS Visit_Month

,STORE_NBR
,TRANS_TYPE
,SUM(Cash_Payment) AS Sum_Cash
,SUM(Card_Payment) AS Sum_Card_Payment
FROM 
(

SELECT  

VISIT_DATE
,VISIT_NBR
,STORE_NBR
,TRANS_TYPE
,AVG(CASH_Payment)AS Cash_Payment
,AVG (CARDS_Payment)AS Card_Payment


FROM  WM_AD_HOC.FACE_FEE_PAYMENT

GROUP BY 1,2,3,4) T GROUP BY 1,2,3,4) b 

ON a.Visit_YEAR= b.Visit_YEAR AND  a.Visit_Month = b.Visit_Month AND a.STORE_NBR= b.STORE_NBR AND a.TRANS_TYPE =b.TRANS_TYPE

ORDER BY a.Visit_YEAR, a.Visit_Month, a.STORE_NBR,a.TRANS_TYPE




