SELECT 
CASE WHEN DATE(DEAL.DMM_APPROVAL_DATE) <= add_months(DEAL.EVENT_END_DATE,2) - DAY(add_months(DEAL.EVENT_END_DATE,2)) Days THEN 'Compliant' ELSE 'Non-Compliant' End AS COMPLIANCE_INDICATOR,
CASE WHEN DATE(DEAL.DMM_APPROVAL_DATE) <= add_months(DEAL.EVENT_BEGIN_DATE,2) - DAY(add_months(DEAL.EVENT_BEGIN_DATE,2)) Days THEN 'Compliant' ELSE 'Non-Compliant' End AS COMPLIANCE_INDICATOR_NEW,
(DEAL.BUYER_APPROVAL_DATE - DEAL.DEAL_CREATE_DATE) AS Buyer_Approval_Days,
(DEAL.VENDOR_APPROVAL_DATE- DEAL.BUYER_APPROVAL_DATE ) AS Vendor_Approval_Days,
CASE WHEN DEAL.VENDOR_APPROVAL_DATE IS NULL THEN  (DATE(DEAL.DMM_APPROVAL_DATE) - DEAL.BUYER_APPROVAL_DATE ) ELSE(DATE(DEAL.DMM_APPROVAL_DATE)- DEAL.VENDOR_APPROVAL_DATE ) END AS DMM_Approval_Days,
CASE 
WHEN DEAL.VENDOR_APPROVAL_DATE IS NULL AND  DEAL.DMM_APPROVAL_DATE IS NULL  THEN  (DEAL.AR_APPROVAL_DATE - DEAL.BUYER_APPROVAL_DATE ) 
WHEN DEAL.DMM_APPROVAL_DATE IS NOT NULL  THEN (DEAL.AR_APPROVAL_DATE -DATE(DEAL.DMM_APPROVAL_DATE))
ELSE  (DEAL.AR_APPROVAL_DATE - DEAL.VENDOR_APPROVAL_DATE ) END AS AR_Approval_Days,
DEAL.*,
 
 CASE WHEN VENDOR_ID IS NULL AND  DMM_USERID IS NULL AND AR_ID IS NULL AND CURRENT_DATE - DATE(BUYER_APPROVAL_DATE) > 90  AND STATUS_GROUP = 'Not Finalized'THEN 'YES' ELSE 'NO' End AS OnlyBuyerSignature
,TIMESTAMP('1900-01-01','00:00:00')  AS  Preivous_Allowance_DMM_SignOffDate,0 AS   TimeGap
,DATE ('1900-01-01') AS   FirstOccurence_0 ,DATE ('1900-01-01') AS  FirstOccurence_1,'NA'AS   New_Allowance_Type



FROM
(SELECT *FROM
(
SELECT 
'US' AS COUNTRY,
T1.DEAL_ID AS ALLOWANCE_ID, 
T1.TOTAL_ALLWNCE_AMT AS AMOUNT,
'D' AS DEAL_OR_COOP,
DATE(T1.DEAL_STATUS_TS) AS DEAL_STATUS_DATE,
T2.DESCR AS ALLOWANCE_TYPE,
T1.BASE_DIV_NBR,
T1.ACCT_DIV_NBR,
T1.SAMS_CATG_NBR,
T1.BUYER_NAME,
DATE(T3.DISC_CHRG_EFF_DATE) AS EVENT_BEGIN_DATE ,
DATE(T3.DISC_CHRG_EXP_DATE) AS EVENT_END_DATE,
DATE(T1.DEAL_CREATE_DATE) AS DEAL_CREATE_DATE,
T1.VENDR_NBR,
T4.VENDR_DEPT_NBR, -- for deals' dept records, dept_nbr in DPDDACHG.VENDOR_DEAL CANNOT be used
T5.VENDR_NAME,
CAST(T6.DISC_CHARG_STAT_CD  AS CHAR(3)) AS DEAL_STATUS_CODE,
CASE WHEN CAST(T6.DISC_CHARG_STAT_CD  AS CHAR(3)) IN ('F','3','4','5','6') THEN 'Finalized'
WHEN CAST(T6.DISC_CHARG_STAT_CD  AS CHAR(3)) IN ('A','R','W','1') THEN 'Not Finalized'
WHEN CAST(T6.DISC_CHARG_STAT_CD  AS CHAR(3)) IN ('D','I','2','7','8','9') THEN 'Rejected/Cancelled/Deleted'ELSE 'Others' END AS STATUS_GROUP,
T6.DISC_CHG_STAT_DESC AS DEAL_STATUS_DESC,

CASE WHEN MONTH(T3.DISC_CHRG_EFF_DATE) = MONTH(T3.DISC_CHRG_EXP_DATE) AND YEAR(T3.DISC_CHRG_EFF_DATE) = YEAR(T3.DISC_CHRG_EXP_DATE) THEN 'NO' ELSE 'YES' End AS Multi_Month,
CASE WHEN MONTH(T1.DEAL_STATUS_TS) = MONTH(T3.DISC_CHRG_EXP_DATE) AND YEAR(T1.DEAL_STATUS_TS) = YEAR(T3.DISC_CHRG_EXP_DATE) THEN 'YES' ELSE 'NO' End AS PROCESD_IN_SME_MTH

FROM 
DPDDACHG.VENDOR_DEAL T1 LEFT JOIN DPDDACHG.DEAL_DEPT T4 ON T1.DEAL_ID  =  T4.DEAL_ID LEFT JOIN DPDDACHG.VENDOR_DEAL_ADDR T5 ON T1.DEAL_ID  =  T5.DEAL_ID
,DPDDACHG.DDA_DISC_TYPE_TEXT T2
,DPDDACHG.DDA_DISCOUNT_CHRG T3
/*,DPDDACHG.DEAL_DEPT T4
/*,DPDDACHG.VENDOR_DEAL_ADDR T5*/*/
,DPDDACHG.DISC_CHRG_STAT_TXT T6
--,DPDDACHG.DEAL_APPROVAL_LOG T7
--,DPDDACHG.DEAL_COMMENT T8
/*,DPDDACHG.DISC_CHRG_FMT_TEXT T9
,DPDDACHG.DISC_CHRG_BAS_TEXT T10*/


WHERE T1.DEAL_ID  =  T3.DEAL_ID 
AND        T1.DISCOUNT_TYPE_CODE = T2.DISCOUNT_TYPE_CODE 
AND        T3.DISC_CHARG_STAT_CD = T6.DISC_CHARG_STAT_CD
AND        T2.LANGUAGE_CODE = '101' 
AND        T6.LANGUAGE_CODE = '101' 
AND        DATE(T1.DEAL_STATUS_TS) BETWEEN (CURRENT_DATE - 25 Months) - (DAY((CURRENT_DATE - 25 Months)) - 1) Days AND (CURRENT_DATE) 
) T_DEAL


LEFT JOIN 
--###############################################################################################################################
-- SUB-TABLE FOR APPROVAL DATA
(
SELECT
APP.*,

CASE WHEN EXTRACT(DAY FROM DMM_APPROVAL_DATE)>= DAY(add_months(DMM_APPROVAL_DATE,0) - DAY(add_months(DMM_APPROVAL_DATE,0)) Days)-5 THEN 'YES' ELSE 'NO' End AS DMMLast5Day,
CASE WHEN EXTRACT(DAY FROM BUYER_APPROVAL_DATE)>= DAY(add_months(BUYER_APPROVAL_DATE,0) - DAY(add_months(BUYER_APPROVAL_DATE,0)) Days)-5 THEN 'YES' ELSE 'NO' End AS BuyerLast5Day

FROM 

(SELECT dal_max.deal_id ALLOWANCE_ID
, dal_buy.last_change_userid BUYER_USER_ID--, dal_buy.approval_status_cd buy_app_status_cd
, dal_sup.last_change_userid VENDOR_ID--, dal_sup.approval_status_cd sup_app_status_cd
 ,dal_dmm.last_change_userid DMM_USERID--, dal_dmm.approval_status_cd dmm_app_status_cd
, dal_ar.last_change_userid AR_ID--, dal_ar.approval_status_cd ar_app_status_cd
,dal_buy.last_change_date BUYER_APPROVAL_DATE
,dal_sup.last_change_date VENDOR_APPROVAL_DATE
/*,dal_dmm.last_change_date DMM_APPROVAL_DATE*/
,TIMESTAMP(CHAR(dal_dmm.last_change_date),'00:00:00') DMM_APPROVAL_DATE

,dal_ar.last_change_date AR_APPROVAL_DATE

FROM 
dpddachg.DEAL_APPROVAL_LOG dal_buy,
dpddachg.DEAL_APPROVAL_LOG dal_sup,
dpddachg.DEAL_APPROVAL_LOG dal_dmm,
dpddachg.DEAL_APPROVAL_LOG dal_ar,
(SELECT deal_id, MAX(version_nbr) max_vers FROM dpddachg.DEAL_APPROVAL_LOG GROUP BY deal_id) dal_max
WHERE dal_buy.deal_id=dal_max.deal_id AND dal_buy.version_nbr = dal_max.max_vers  AND dal_buy.APPV_LEVEL_CODE = 1 
AND dal_sup.deal_id=dal_max.deal_id AND dal_sup.version_nbr = dal_max.max_vers AND dal_sup.APPV_LEVEL_CODE = 2
AND dal_dmm.deal_id=dal_max.deal_id AND dal_dmm.version_nbr = dal_max.max_vers AND dal_dmm.APPV_LEVEL_CODE = 3
AND dal_ar.deal_id=dal_max.deal_id AND dal_ar.version_nbr = dal_max.max_vers AND dal_ar.APPV_LEVEL_CODE = 99) APP


) K

ON T_DEAL.Allowance_ID = K.ALLOWANCE_ID) DEAL


UNION


SELECT
CASE WHEN DATE(COOP.DMM_APPROVAL_DATE) <= ADD_MONTHS(COOP.EVENT_END_DATE,2) - DAY(ADD_MONTHS(COOP.EVENT_END_DATE,2)) Days THEN 'Compliant' ELSE 'Non-Compliant' End AS COMPLIANCE_INDICATOR,
CASE WHEN DATE(COOP.DMM_APPROVAL_DATE) <= ADD_MONTHS(COOP.EVENT_BEGIN_DATE,2) - DAY(ADD_MONTHS(COOP.EVENT_BEGIN_DATE,2)) Days THEN 'Compliant' ELSE 'Non-Compliant' End AS COMPLIANCE_INDICATOR_NEW,

(DATE(COOP.BUYER_APPROVAL_DATE) - COOP.DEAL_CREATE_DATE) AS Buyer_Approval_Days,
(DATE(COOP.VENDOR_APPROVAL_DATE)- DATE(COOP.BUYER_APPROVAL_DATE )) AS Vendor_Approval_Days,
CASE WHEN COOP.VENDOR_APPROVAL_DATE IS NULL THEN  (DATE(COOP.DMM_APPROVAL_DATE) - DATE(COOP.BUYER_APPROVAL_DATE )) ELSE(DATE(COOP.DMM_APPROVAL_DATE) - DATE(COOP.VENDOR_APPROVAL_DATE) ) END AS DMM_Approval_Days,
CASE 
WHEN COOP.VENDOR_APPROVAL_DATE IS NULL AND  COOP.DMM_APPROVAL_DATE IS NULL  THEN  (DATE(COOP.AR_APPROVAL_DATE) - DATE(COOP.BUYER_APPROVAL_DATE ))
WHEN COOP.DMM_APPROVAL_DATE IS NOT NULL  THEN (DATE(COOP.AR_APPROVAL_DATE) -DATE( COOP.DMM_APPROVAL_DATE ))
ELSE  (DATE(COOP.AR_APPROVAL_DATE) - DATE(COOP.VENDOR_APPROVAL_DATE) ) END AS AR_Approval_Days,


COOP.*,
CASE WHEN VENDOR_ID IS NULL AND  DMM_USERID IS NULL AND AR_ID IS NULL AND CURRENT_DATE - DATE(BUYER_APPROVAL_DATE) > 90  AND STATUS_GROUP = 'Not Finalized'THEN 'YES' ELSE 'NO' End AS OnlyBuyerSignature,

CASE WHEN DEAL_STATUS_DESC <> 'DMM REJECTED' THEN
 MAX(DMM_APPROVAL_DATE)
       OVER(PARTITION BY DMM_USERID, DATE(DMM_APPROVAL_DATE)  ORDER BY DMM_APPROVAL_DATE
            ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING) ELSE NULL END AS Preivous_Allowance_DMM_SignOffDate,--Lag_ --Yesterday
CASE WHEN DEAL_STATUS_DESC <> 'DMM REJECTED' THEN 
 DMM_APPROVAL_DATE - MAX(DMM_APPROVAL_DATE)
       OVER(PARTITION BY DMM_USERID, DATE(DMM_APPROVAL_DATE)  ORDER BY DMM_APPROVAL_DATE ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING) 
	   ELSE NULL END AS TimeGap,

KRI03.FirstOccurence_0,KRI03.FirstOccurence_1,KRI03.New_Allowance_Type
	   
FROM 
(SELECT *FROM

(SELECT 
'US' AS COUNTRY,  
A.DEAL_ID AS ALLOWANCE_ID, 
A.TOTAL_ALLWNCE_AMT AS AMOUNT, 
A.COOP_DEAL_CODE AS DEAL_OR_COOP, 
DATE(A.DEAL_STATUS_TS) AS DEAL_STATUS_DATE, 
/*MONTH(A.DEAL_STATUS_TS) AS DEAL_STATUS_MONTH,
YEAR(A.DEAL_STATUS_TS) AS DEAL_STATUS_YEAR,*/
B.DESCR AS ALLOWANCE_TYPE, 
A.BASE_DIV_NBR,
A.ACCT_DIV_NBR, 
A.SAMS_CATG_NBR,
A.BUYER_NAME, 
DATE(A.VNDR_DEAL_EFF_DATE) AS EVENT_BEGIN_DATE,
DATE(A.VNDR_DEAL_EXP_DATE) AS EVENT_END_DATE,
DATE(A.DEAL_CREATE_DATE) AS DEAL_CREATE_DATE,
A.VENDR_NBR,
A.VENDR_DEPT_NBR,
G.VENDR_NAME,
CAST(A.DEAL_STATUS_CODE AS CHAR(3)) AS DEAL_STATUS_CODE,
CASE WHEN A.DEAL_STATUS_CODE IN (9,11,15,16)  THEN 'Finalized'WHEN A.DEAL_STATUS_CODE IN (1,2,3,5,17,18,30,31,8,12) THEN 'Not Finalized'WHEN A.DEAL_STATUS_CODE IN(4,6,7,19,20,14,40,41,10,13) THEN 'Rejected/Cancelled/Deleted'
ELSE 'Others' 
END AS STATUS_GROUP,
C.DEAL_STATUS_DESC,
CASE WHEN MONTH(A.VNDR_DEAL_EFF_DATE) = MONTH(A.VNDR_DEAL_EXP_DATE) AND YEAR(A.VNDR_DEAL_EFF_DATE) = YEAR(A.VNDR_DEAL_EXP_DATE)THEN 'NO' ELSE 'YES' End AS Multi_Month,
CASE WHEN MONTH(A.DEAL_STATUS_TS) = MONTH(A.VNDR_DEAL_EXP_DATE) AND YEAR(A.DEAL_STATUS_TS) = YEAR(A.VNDR_DEAL_EXP_DATE) THEN 'YES' ELSE 'NO' End AS PROCESD_IN_SME_MTH


FROM 
DPDDACHG.VENDOR_DEAL A
,DPDDACHG.DDA_DISC_TYPE_TEXT B
,DPDDACHG.DEAL_STATUS_TEXT C
,DPDDACHG.VENDOR_DEAL_ADDR G
WHERE A.DISCOUNT_TYPE_CODE = B.DISCOUNT_TYPE_CODE 
AND A.DEAL_STATUS_CODE = C.DEAL_STATUS_CODE 
AND  C.LANGUAGE_CODE = '101'
AND A.DEAL_ID = G.DEAL_ID
AND B.LANGUAGE_CODE='101' 
AND A.COOP_DEAL_CODE = 'C'
--AND DATE(A.DEAL_STATUS_TS) BETWEEN (CURRENT_DATE - 16 Months) - (DAY((CURRENT_DATE - 16 Months)) - 1) Days AND (CURRENT_DATE) 
AND DATE(A.DEAL_STATUS_TS) BETWEEN (CURRENT_DATE - 25 Months) - (DAY((CURRENT_DATE - 25 Months)) - 1) Days AND (CURRENT_DATE) 
) T_COOP

LEFT JOIN 

(SELECT ALLOWANCE_ID,
BUYER_USER_ID,
VENDOR_ID,
DMM_USERID,
AR_ID,
DATE(BUYER_APPROVAL_DATE) AS BUYER_APPROVAL_DATE,
DATE(VENDOR_APPROVAL_DATE) AS VENDOR_APPROVAL_DATE,
DMM_APPROVAL_DATE,
DATE(AR_APPROVAL_DATE)AS AR_APPROVAL_DATE,


CASE WHEN EXTRACT(DAY FROM DMM_APPROVAL_DATE)>= DAY(ADD_MONTHS(DMM_APPROVAL_DATE,0) - DAY(ADD_MONTHS(DMM_APPROVAL_DATE,0)) Days)-5 THEN 'YES' ELSE 'NO' End AS DMMLast5Day,
CASE WHEN EXTRACT(DAY FROM BUYER_APPROVAL_DATE)>= DAY(ADD_MONTHS(BUYER_APPROVAL_DATE,0) - DAY(ADD_MONTHS(BUYER_APPROVAL_DATE,0)) Days)-5 THEN 'YES' ELSE 'NO' End AS BuyerLast5Day--,
--CASE WHEN EXTRACT(DAY FROM DMM_APPROVAL_DATE)= DAY(ADD_MONTHS(DMM_APPROVAL_DATE,0) - DAY(ADD_MONTHS(DMM_APPROVAL_DATE,0)) Days) AND  CAST(EXTRACT (MINUTE FROM DMM_APPROVAL_DATE)AS INTEGER) >=58 THEN 'YES' ELSE 'NO' End AS DMMLast2Min
---,BUYER_COMMENT,
---VENDOR_COMMENT,
---DMM_COMMENT,
---AR_COMMENT,
---OTHER_COMMENT,
---MODIFICATION_SCREEN
FROM 
(SELECT * FROM (
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--- Approval Levels, Dates in 1 Table
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
(SELECT * FROM (
(SELECT * FROM(
(SELECT * FROM (
(SELECT DEAL_ID AS Allowance_ID, DEAL_AUTHOR_USERID AS BUYER_USER_ID,DEAL_AUTHOR_TS AS BUYER_APPROVAL_DATE
FROM  DPDDACHG.DEAL_AUTHORIZATION WHERE APPRVL_LEVEL_CODE IN (1)) s1
LEFT JOIN 
(SELECT DEAL_ID, DEAL_AUTHOR_USERID AS VENDOR_ID,DEAL_AUTHOR_TS AS VENDOR_APPROVAL_DATE 
FROM  DPDDACHG.DEAL_AUTHORIZATION WHERE APPRVL_LEVEL_CODE IN (2)) s2
ON s1.Allowance_ID = s2.DEAL_ID)) S1
LEFT JOIN 
(SELECT DEAL_ID, DEAL_AUTHOR_USERID AS DMM_USERID,DEAL_AUTHOR_TS AS DMM_APPROVAL_DATE
FROM  DPDDACHG.DEAL_AUTHORIZATION WHERE APPRVL_LEVEL_CODE IN (3))s4
ON S1.Allowance_ID = s4.DEAL_ID))S2
LEFT JOIN 
(SELECT DEAL_ID, DEAL_AUTHOR_USERID AS AR_ID,DEAL_AUTHOR_TS  AS AR_APPROVAL_DATE
FROM  DPDDACHG.DEAL_AUTHORIZATION WHERE APPRVL_LEVEL_CODE IN (4))s5
ON S2.Allowance_ID = s5.DEAL_ID)))))T_AP_Level ON T_COOP.ALLOWANCE_ID = T_AP_Level.Allowance_ID



) COOP

LEFT JOIN 

(SELECT T1.*, T2.FirstOccurence_1,New_Allowance_Type
FROM 
(SELECT A.DISCOUNT_TYPE_CODE, B.DESCR AS ALLOWANCE_TYPE, MIN(DATE(A.DEAL_STATUS_TS)) FirstOccurence_0
FROM DPDDACHG.VENDOR_DEAL A ,DPDDACHG.DDA_DISC_TYPE_TEXT B
WHERE A.DISCOUNT_TYPE_CODE = B.DISCOUNT_TYPE_CODE 
AND B.LANGUAGE_CODE='101' 
AND A.COOP_DEAL_CODE = 'C'
GROUP BY A.DISCOUNT_TYPE_CODE,B.DESCR) T1


RIGHT JOIN (

SELECT A.DISCOUNT_TYPE_CODE,MIN(DATE(A.DEAL_STATUS_TS)) FirstOccurence_1, CASE WHEN MONTH( (CURRENT_DATE - 25 Months) - (DAY((CURRENT_DATE - 25 Months)) - 1) Days )= MONTH(MIN(DATE(A.DEAL_STATUS_TS))) THEN 'NO' ELSE 'YES' END AS New_Allowance_Type
FROM DPDDACHG.VENDOR_DEAL A
WHERE DATE(A.DEAL_STATUS_TS) BETWEEN (CURRENT_DATE - 25 Months) - (DAY((CURRENT_DATE - 25 Months)) - 1) Days AND (CURRENT_DATE) 
AND A.COOP_DEAL_CODE = 'C'
GROUP BY A.DISCOUNT_TYPE_CODE) T2 ON T1.DISCOUNT_TYPE_CODE = T2.DISCOUNT_TYPE_CODE) KRI03 ON COOP.ALLOWANCE_TYPE = KRI03.ALLOWANCE_TYPE

ORDER BY DMM_USERID, DMM_APPROVAL_DATE